### PR TITLE
Fixed it.

### PR DESCRIPTION
**Pull request by HBIDamian**
Basically i fixed the plugin's problems. I have tested it too, and it works.
( this problem was in the plugin.yml. It was not correct,

At the moment, its only active IF you have have not upgraded to php7. If you havem then simply replace 
api: 1.14.0 with
api: 2.0.0

### CODE REVIEW

**Comment by HBIDamian** [comment]
Also, could I upload it to PocketMine Plugin repository? It would help people quite a lot.

**Comment by SirGamer** [comment]
Hey,

You cannot do so, as this plugin **isn't** yours.

**Comment by SirGamer** [comment]
Also, just because you changed the API stuff, that doesn't mean your an author.

**Comment by HBIDamian** [comment]
SirGamer, actually, i did all of the pkugin fixes, and basically brought it to life. Hay... its just give tiny bit of credit to me. THATS ive asked @Gumbrat not @SirGamer. anyway. ive made an alternative one that does much more. its not on my g.h. yet, but its in the PocketMine approval list already. (gived reference to Gumbrat.

**Comment by HBIDamian** [comment]
Also, @SirGamer, if you wish to make a complaint, email it to
nobody@cares.com

**Comment by SirGamer** [comment]
K, you're somewhat immature.

**Comment by SirGamer** [comment]
Send a e-mail to:

fbi@co.gov

**Comment by HBIDamian** [comment]
Ha, thats also immature. The FBI will not bother with petty stuff like asking "Can I upload your content to PM" Think before your actions. No! so "Sonny-Boy" be quiet before it really gets you into trouble

**Comment by Gumbrat** [comment]
@thedeibo Thanks for the help bud

**Comment by SirGamer** [comment]
Gumbrat, maybe lock this, this immature "deibo" didn't even capitalize his own username.

**Comment by MichaelM04** [comment]
@SirGamer Your really stupid man he ALREADY accepted the pull request 6 hours ago and had other times as well. If your not providing a  contribution why even bother to comment let alone fight! Nobody wants to read your stupid comments go fight elsewhere

**Comment by HBIDamian** [comment]
@SirGamer thanks for your feedback. Tradically, ive misplaced exatly what you've said, in the pits of NO ONE CARES!

But if it so pleases you, il add my capitals in my name. ( actually, it used to be caps, but github changed it )

**Comment by HBIDamian** [comment]
Ok your highness,,,, Its changed. Now do everyone a favour, and delete your github, turn off your router, grab a hammer, and smash it to bits. Then, do the same with your computer. Basically, you are not wanted online, or even offline

**Comment by SirGamer** [comment]
I wish to not fight anymore, please shut up.

**Comment by Gumbrat** [comment]
Hey @TheDeibo thanks for the help but.. Id like to take it fr here. Please don't post it....
I'd be pretty upset. 
Thank you :)

**Comment by HBIDamian** [comment]
ok. If you wish to upload to PocketMine, it must have new and more  features, because it is too small and simple.

on my github, i am actually making a bigger plugin which may include this in it or not.... havent decided.
But, if I decide to include it, i may add a thankyou note to you,

but like I said, you need to make the plugin BIGGER if you wish to upload it to PocketMine

**Pull request merged**
