### PR TITLE
Fixed a few issues

### PR DESCRIPTION
**Pull request by MinecrafterPH**

### CODE REVIEW

**Comment by MichaelM04** [comment]
Still get a error with the new one 1:12:52] [CRITICAL]: pocketmine\utils\PluginException: "Couldn't load plugin UnlimitedSlots: main class not found" (EXCEPTION) in "/src/pocketmine/plugin/PharPluginLoader" at line 70
[11:12:52] [EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

If you fix could you convert to .phar

**Comment by MinecrafterPH** [comment]
I don't get any errors. This is not yet merged so don't download the ZIP here. Instead, download this PHAR: http://pmt.mcpe.me/data/phars/phar_UnlimitedSlots-master(1)_GNPGu1e6pIZnaSH.phar

**Comment by Gumbrat** [comment]
Forgive me this is my first time using github

**Comment by MichaelM04** [comment]
No problem I'm learning to be a dev myself

**Comment by Gumbrat** [comment]
Thanks man

**Comment by MinecrafterPH** [comment]
Could you please merge it?

**Comment by MichaelM04** [comment]
Do you mean .phar hopefully here's the .phar

**Comment by Gumbrat** [comment]
I'm fixing up a few things k

**Comment by MichaelM04** [comment]
[UnlimitedSlots.phar.zip](https://github.com/Gumbrat/UnlimitedSlots/files/54255/UnlimitedSlots.phar.zip)
Here's The Phar Just UnZip

**Comment by HBIDamian** [comment]
I have noticed the code isnt right. i have corrected it. All you meed to do is go on 
https://github.com/Gumbrat/UnlimitedSlots/pull/4 and press accept

**Pull request closed without merging**
